### ISSUE TITLE
Possibility to optionally remove the boost dependency?

### ISSUE THREAD

**Issue by jraygauthier** [SodiumFRP/sodium-cxx#2]
I'm navigating the code and it seems in the presence of C++11, the principal need for
boost is to draw its `optional` class and a secondary need seems to be for its
`intrusive_ptr` class.

It seems to me it wouldn't be too hard to introduce a simple drop-in replacement for
both, thus making this library self-contained.

**Comment by jraygauthier** [comment]
Something like [akrzemi1/Optional: optional (nullable) objects for C++14](https://github.com/akrzemi1/Optional) would be a proper replacement.

**Comment by the-real-blackh** [comment]
Since boost::optional is part of the API, it should be able to support boost::optional. I'm happy to put in a compile-time switch for this. But, it's not a priority for me. If you'd like to do the work, I'd happily accept it.

**Comment by jraygauthier** [comment]
Note yet quite there. Sometimes, the projects I work with don't allows for depending on boost. If such situation presents itself, I will know you're open to this kind of modifications and I should open a pull request with the required changes. You can close the issue if you would like.

**Comment by the-real-blackh** [comment]
Great.
