### ISSUE TITLE
Current version of the library?

### ISSUE THREAD

**Issue by jraygauthier** [SodiumFRP/sodium-cxx#3]
Is it aligned on the version in other language at https://github.com/SodiumFRP/sodium/releases ?

**Comment by the-real-blackh** [comment]
No it isn't. Let me know if want version number tags. I'll give it a version number after I've fixed a few things.

**Comment by jraygauthier** [comment]
Nothing pressing yet. I packaged the library (locally) using nix package manager. As this required a version, I thought it might be a good idea to ask. When you have a version I will be able to submit the package to `nixpkgs` (the shared package description repo).

**Comment by Confuset** [comment]
Same 'issue' here. I wanted to package a version of sodium with https://conan.io and a version number is needed. whats the status?

Currently reading through your book. Good read :-)

**Comment by the-real-blackh** [comment]
I just tagged the current version as 0.9.0. Glad you're enjoying the book!
